#!/usr/bin/env python3
"""维护持久的 output/grfal/gallery.html：三分区累积批次。"""
from __future__ import annotations

import html
import shutil
import subprocess
import time
from pathlib import Path

THUMB_MAX_PX = 512


def _make_thumb(src: Path, thumb: Path) -> bool:
    """用 macOS sips 生成 512px JPG 缩略图。已存在且不旧则跳过。成功返回 True。"""
    if thumb.exists() and thumb.stat().st_mtime >= src.stat().st_mtime:
        return True
    thumb.parent.mkdir(parents=True, exist_ok=True)
    try:
        subprocess.run(
            ["sips", "-Z", str(THUMB_MAX_PX), "-s", "format", "jpeg",
             "-s", "formatOptions", "80", str(src), "--out", str(thumb)],
            check=True, capture_output=True, timeout=30,
        )
        return True
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired, FileNotFoundError):
        return False

MODULE_TITLES = {
    "ui": "活动界面 UI",
    "chest": "宝箱图标",
    "item": "活动道具",
}

MARKER = {m: f"<!-- BATCHES_{m.upper()} -->" for m in MODULE_TITLES}

_TEMPLATE = """<!DOCTYPE html>
<html lang="zh">
<head>
<meta charset="utf-8">
<title>P2 Art Gallery — grfal</title>
<style>
  body { font-family: -apple-system, "PingFang SC", sans-serif; margin:0; background:#f5f5f7; color:#1d1d1f; }
  header { padding:14px 28px; background:#fff; border-bottom:1px solid #e5e5e7; position:sticky; top:0; z-index:10; display:flex; align-items:center; gap:16px; }
  header h1 { font-size:18px; margin:0; font-weight:600; }
  header .hint { color:#86868b; font-size:13px; }
  nav { display:flex; gap:4px; }
  nav a { padding:6px 12px; border-radius:6px; text-decoration:none; color:#1d1d1f; font-size:13px; }
  nav a:hover { background:#f5f5f7; }
  main { max-width:1600px; margin:0 auto; padding:24px; }
  section { margin-bottom:48px; }
  section > h2 { font-size:20px; margin:0 0 16px; padding-bottom:10px; border-bottom:2px solid #0071e3; }
  .batch { background:#fff; border-radius:12px; padding:20px; margin-bottom:20px; box-shadow:0 1px 3px rgba(0,0,0,.06); }
  .batch-meta { color:#86868b; font-size:12px; margin-bottom:10px; display:flex; flex-wrap:wrap; gap:16px; }
  .batch-meta b { color:#1d1d1f; font-weight:500; }
  .batch-prompt { background:#f5f5f7; border-radius:8px; padding:12px 16px; font-size:13px; line-height:1.6; margin-bottom:14px; white-space:pre-wrap; word-break:break-word; }
  .refs { display:flex; gap:8px; flex-wrap:wrap; margin-bottom:14px; }
  .refs .ref { display:flex; flex-direction:column; align-items:center; gap:4px; }
  .refs img { height:80px; border-radius:6px; border:1px solid #d2d2d7; }
  .refs .ref-label { font-size:11px; color:#86868b; }
  .grid { display:grid; grid-template-columns:repeat(auto-fill, minmax(180px, 1fr)); gap:12px; }
  .cell { position:relative; border-radius:8px; overflow:hidden; background:#000; aspect-ratio:1; cursor:pointer; }
  .cell img { width:100%; height:100%; object-fit:contain; display:block; }
  .cell .badge { position:absolute; top:6px; left:6px; padding:2px 8px; border-radius:4px; font-size:10px; color:#fff; font-weight:600; letter-spacing:.5px; text-transform:uppercase; box-shadow:0 1px 3px rgba(0,0,0,.3); }
  .cell .actions { position:absolute; bottom:0; left:0; right:0; background:linear-gradient(to top, rgba(0,0,0,.7), transparent); padding:8px; display:flex; gap:6px; opacity:0; transition:opacity .15s; }
  .cell:hover .actions { opacity:1; }
  .cell button { flex:1; border:none; border-radius:4px; padding:5px 8px; font-size:11px; cursor:pointer; background:rgba(255,255,255,.9); color:#1d1d1f; }
  .cell button:hover { background:#fff; }
  .cell button.ok { background:#34c759; color:#fff; }
  .empty { color:#86868b; font-size:14px; padding:20px; background:#fff; border-radius:12px; text-align:center; }
  footer { text-align:center; padding:40px; color:#86868b; font-size:12px; }
</style>
</head>
<body>
<header>
  <h1>P2 Art Gallery</h1>
  <nav>__NAV__</nav>
  <span class="hint">grfal · 点图片下方按钮复制到剪贴板</span>
</header>
<main>
__SECTIONS__
</main>
<footer>generated by .claude/skills/p2-art-gen</footer>
<script>
async function copyImg(btn, src) {
  try {
    const r = await fetch(src);
    const blob = await r.blob();
    const type = blob.type || 'image/png';
    await navigator.clipboard.write([new ClipboardItem({[type]: blob})]);
    const label = btn.textContent;
    btn.textContent = '✓ 已复制';
    btn.classList.add('ok');
    setTimeout(() => { btn.textContent = label; btn.classList.remove('ok'); }, 1500);
  } catch (e) {
    alert('复制失败: ' + e.message);
  }
}
async function copyPath(btn, path) {
  try {
    await navigator.clipboard.writeText(path);
    const label = btn.textContent;
    btn.textContent = '✓ 路径已复制';
    btn.classList.add('ok');
    setTimeout(() => { btn.textContent = label; btn.classList.remove('ok'); }, 1500);
  } catch (e) { alert('失败: ' + e.message); }
}
</script>
</body>
</html>
"""


def _init_html(gallery_path: Path):
    nav_links = " ".join(f'<a href="#{m}">{title}</a>' for m, title in MODULE_TITLES.items())
    sections = []
    for m, title in MODULE_TITLES.items():
        sections.append(
            f'<section id="{m}">\n  <h2>{title}</h2>\n  {MARKER[m]}\n  '
            f'<div class="empty empty-{m}">暂无生成，运行 skill 后自动填充</div>\n</section>'
        )
    out = _TEMPLATE.replace("__NAV__", nav_links).replace("__SECTIONS__", "\n".join(sections))
    gallery_path.parent.mkdir(parents=True, exist_ok=True)
    gallery_path.write_text(out, encoding="utf-8")


ENGINE_COLOR = {
    "gpt": "#10a37f",
    "gemini": "#4285f4",
    "seedream": "#ff6b00",
    "flux": "#000",
    "runway": "#111",
    "wan": "#d9222a",
    "qwen": "#615ced",
    "ideogram": "#e84a7f",
    "hunyuan": "#2563eb",
    "grok": "#000",
    "zimage": "#0ea5e9",
    "firered": "#d92b2b",
    "vidu": "#7c3aed",
}

# 产品名展示（grfal API 键 → 用户看到的名字）
ENGINE_DISPLAY = {
    "gemini": "nano-banana",    # 谷歌 Nano Banana 2
}


def append_batch(
    gallery_path: Path,
    module: str,
    timestamp: str,
    prompt: str,
    engines: list[str],
    ref_paths: list[str],
    items: list[dict],     # [{"path": "images/chest/xxx.png", "engine": "gpt"}, ...]
    duration_s: float,
    # legacy aliases for backward compat
    engine: str | None = None,
    image_paths: list[str] | None = None,
):
    """把一个新批次插入到 gallery.html 对应模块区的最顶部。"""
    # legacy 兼容：旧调用方传 engine + image_paths
    if not items and image_paths is not None:
        eng = engine or (engines[0] if engines else "gpt")
        items = [{"path": p, "engine": eng} for p in image_paths]
    if not engines and engine:
        engines = [engine]

    if not gallery_path.exists():
        _init_html(gallery_path)
    doc = gallery_path.read_text(encoding="utf-8")

    # 渲染 refs：外部路径的 ref 图拷贝到 gallery 本地 refs/ 目录，避免 Chrome file:// 跨目录限制
    ref_html = []
    gallery_dir = gallery_path.parent
    refs_dir = gallery_dir / "refs" / module
    refs_dir.mkdir(parents=True, exist_ok=True)
    for i, rp in enumerate(ref_paths):
        rp_abs = Path(rp).resolve()
        # 如果已经在 gallery_dir 下，直接用相对路径；否则拷贝到 refs/ 后再引用
        try:
            rel = rp_abs.relative_to(gallery_dir)
            ref_src = str(rel)
        except ValueError:
            local = refs_dir / rp_abs.name
            if not local.exists() or local.stat().st_size != rp_abs.stat().st_size:
                shutil.copy2(rp_abs, local)
            ref_src = str(local.relative_to(gallery_dir))
        label = "竞品" if (module == "ui" and i == 0) else "P2 锚点"
        ref_src_escaped = html.escape(ref_src, quote=True)
        ref_html.append(
            f'<div class="ref">'
            f'<img src="{ref_src_escaped}" alt="{label}">'
            f'<span class="ref-label">{label}：{html.escape(rp_abs.name)}</span>'
            f'</div>'
        )
    refs_block = f'<div class="refs">{"".join(ref_html)}</div>' if ref_html else ""

    # 渲染 grid（生成 512px JPG 缩略图，避开 Chrome 同屏渲染 4K PNG 崩掉变黑）
    cells = []
    for i, it in enumerate(items):
        rel_path = it["path"]
        eng = it.get("engine", "?")
        rel_escaped = html.escape(rel_path, quote=True)
        abs_path = (gallery_path.parent / rel_path).resolve()
        abs_escaped = html.escape(str(abs_path), quote=True)
        # thumb: thumbs/ 镜像目录 + .jpg 后缀
        thumb_rel = Path("thumbs") / Path(rel_path).with_suffix(".jpg")
        thumb_abs = gallery_path.parent / thumb_rel
        thumb_src = str(thumb_rel) if _make_thumb(abs_path, thumb_abs) else rel_path
        thumb_escaped = html.escape(thumb_src, quote=True)
        color = ENGINE_COLOR.get(eng, "#666")
        eng_display = ENGINE_DISPLAY.get(eng, eng)
        cells.append(
            f'<div class="cell">'
            f'<img src="{thumb_escaped}" alt="{i}" loading="lazy">'
            f'<div class="badge" style="background:{color};">{html.escape(eng_display)}</div>'
            f'<div class="actions">'
            f'<button onclick="copyImg(this, \'{rel_escaped}\')">复制图片</button>'
            f'<button onclick="copyPath(this, \'{abs_escaped}\')">复制路径</button>'
            f'</div>'
            f'</div>'
        )
    grid_block = f'<div class="grid">{"".join(cells)}</div>'

    engines_label = " + ".join(
        f"{ENGINE_DISPLAY.get(e, e)} × {sum(1 for it in items if it['engine']==e)}"
        for e in engines
    )

    batch_html = (
        f'<div class="batch">'
        f'<div class="batch-meta">'
        f'<span><b>{time.strftime("%Y-%m-%d %H:%M", time.strptime(timestamp, "%Y%m%d_%H%M%S"))}</b></span>'
        f'<span>引擎: <b>{html.escape(engines_label)}</b></span>'
        f'<span>张数: <b>{len(items)}</b></span>'
        f'<span>耗时: <b>{duration_s:.0f}s</b></span>'
        f'</div>'
        f'<div class="batch-prompt">{html.escape(prompt)}</div>'
        f'{refs_block}'
        f'{grid_block}'
        f'</div>'
    )

    # 插到 marker 前 + 清掉 empty 占位
    marker = MARKER[module]
    if marker not in doc:
        # 老版本文件没有 marker，重建
        _init_html(gallery_path)
        doc = gallery_path.read_text(encoding="utf-8")

    # 移除该模块的 empty 占位（如果有）
    doc = doc.replace(f'<div class="empty empty-{module}">暂无生成，运行 skill 后自动填充</div>\n', "")
    # 在 marker 后插入（让最新批次出现在模块顶部）
    doc = doc.replace(marker, f"{marker}\n{batch_html}", 1)
    gallery_path.write_text(doc, encoding="utf-8")
