/* ══════════════════════════════════════════════════════════════════════
   活动全集 · 数据源
   ----------------------------------------------------------------------
   来源：① 转正答辩 PPT（2025-12-08，工作亮点汇总 + 4 个重点成果）
        ② reports/index.html 的 17 份回归报告结论
        ③ 2112 activity_config_qa 全表 2065 行（按 id 精确锁定实例）
        ④ docs/ 下的策划案
   规则：数值一律来自上面四个来源，没有来源的写 null，不编。
        增删活动只改本文件的 ACTS 数组，页面自动跟。
   ══════════════════════════════════════════════════════════════════════ */

const GROUPS = [
  { key: "minigame", name: "小游戏 / 独立玩法", icon: "🎮",
    desc: "自带规则与关卡的独立玩法，付费点铺在推进路径上" },
  { key: "gacha",    name: "抽奖 / GACHA",      icon: "🎰",
    desc: "随机型付费，本体抽奖坑位与独立投放" },
  { key: "pay",      name: "礼包与付费结构",     icon: "💰",
    desc: "不新做玩法，改的是付费结构与货架" },
  { key: "cosmetic", name: "外显 / 收藏",       icon: "✨",
    desc: "纯外观资产，社交展示与收藏驱动" },
  { key: "pitch",    name: "立项 / 未上线",      icon: "📐",
    desc: "已成文的立项案，含被推翻的" },
];

const ACTS = [
  /* ─────────────── 小游戏 / 独立玩法 ─────────────── */
  {
    id: "dighole", group: "minigame", name: "挖孔小游戏", icon: "⛏️",
    status: "已上线", origin: "转正答辩", firstAt: "2025 下半年", seasons: "9 期（旧模板 → 新挖孔）",
    oneLine: "消耗锄头挖出指定图形过关，礼包投放通关道具",
    background: "传统礼包形式付费下降明显，小游戏形式已验证。挖孔是大富翁之后的第一个小游戏，目标提升 ARPU。",
    originality: [
      "关卡与图形判定规则自研（treasure 形状 + tool_type 横/纵/炸三类道具）",
      "奖励关卡从固定出现改为动态触发：检测玩家已过前置关卡且锄头低于预期消耗时才给",
      "配合奖励关卡触发限时礼包，把付费点铺在卡关瞬间",
      "二期加图鉴 + 评分（Jira P2DEV-144522）",
    ],
    config: {
      main: ["21127899 新挖孔（拓荒七期 / 周年二期）", "21127575 老挖孔（登月八期）"],
      tables: ["2183 关卡", "2175 形状", "2116 兑换", "2121 进度", "2011 IAP", "2013 礼包", "1111 道具"],
      note: "新旧两套模板并行，兑换币已拆分；老挖孔行列字段是大写 Row/Col",
    },
    data: [
      { label: "拓荒七期营收", value: "$395,750", note: "挖孔系列新高 · 占全节日付费 36.1%", src: "reports/dighole7" },
      { label: "猎豹染色玩家均消费", value: "$561", note: "符合数值设置预期区间", src: "转正答辩 p10" },
      { label: "小额礼包转化", value: "最优", note: "超过 $4.99 档位转化下滑，后续持续保持小额", src: "转正答辩 p9" },
    ],
    issues: ["操作区域过小、关卡核心目标突出不到位", "活动坑深有限", "投放奖励吸引力不够"],
    assets: { report: "../reports/index.html#dighole7", report2: "../reports/index.html#dighole9",
              design: null, skill: "dighole-simulator / dighole-data-regression" },
  },
  {
    id: "winecup", group: "minigame", name: "猜酒杯（备餐大挑战）", icon: "🍶",
    status: "已上线 · 二期草案中", origin: "2026 新增", firstAt: "2026-06 深海节", seasons: "2 期（深海 / 登月）",
    oneLine: "一排统一造型只换色的秘制酱料瓶，拖进浓汤猜哪瓶配哪锅",
    background: "补小游戏品类。谜题纯考颜色判断，美术只需单模型 recolor，是低美术成本、高关卡量的形态。",
    originality: [
      "玩法本体：酱料配浓汤（不是酒）—— 全统一造型只换颜色，美术成本压到单模型",
      "二期诊断出真问题不在入口/定价，在漏斗死区 L5–L15（到达 L15 仅 2.8% vs 挖孔 43.7%）",
      "二期三支柱：阶梯点火点前移到 L5-L8 / 搬挖孔鲸鱼深度引擎 / 档期移出 day1",
      "收集系统「招牌料理·深海宴席收藏」40 道菜 / 5 桌，与做菜玩法同源",
    ],
    config: { main: ["21127900 猜酒杯小游戏"], tables: ["2011 iap_status 门槛", "ods_user_event 漏斗"],
              note: "门槛在 2011 iap_status；漏斗口径 $.level vs $.level_id 两家 key 不同" },
    data: [
      { label: "深海首期 · 付费转化", value: "3.6%", note: "对比挖孔 14.8%", src: "reports/winecup" },
      { label: "到达 L15", value: "2.8%", note: "挖孔同口径 43.7%，差 15.6×", src: "reports/winecup" },
      { label: "登月期收官", value: "比深海 −6.4%", note: "输在中段，非首日", src: "reports/moonwinecup" },
    ],
    issues: ["漏斗死区 L5–L15：免费手套只够到 ~L6，值钱阶梯却在 L15", "档期压在 day1 与 11 个活动抢钱包"],
    assets: { report: "../reports/index.html#winecup", report2: "../reports/index.html#moonwinecup",
              design: "../docs/winecup_p2_design/index.html", skill: null },
  },
  {
    id: "metro", group: "minigame", name: "挖矿合成小游戏", icon: "🧱",
    status: "已上线", origin: "2026 新增", firstAt: "2026", seasons: "多期（schema3/4/5 三档并行）",
    oneLine: "网格掉落合成（2048 × 合成大西瓜），分数进排行榜 + 兑换代币",
    background: "补小游戏品类，横屏网格掉落形态在竞品（Pop Epoch · Life Incubator Lab）已验证。",
    originality: [
      "三 schema 并行（3/4/5）覆盖不同 R 段，一套底层三份内容",
      "体力是唯一硬闸门，三条来源：自然恢复 / 任务产出 / 付费购买",
      "自净化机制：盘面最低级方块被清，带豁免触发块规则（防把刚合出的方块清掉）",
      "配套挖矿累积任务作为独立活动挂在旁边",
    ],
    config: { main: ["21129562 26周年庆-挖矿累积任务", "3510 合成小游戏本体"],
              tables: ["3510", "2112", "2013（106 行）", "2011", "2115", "2118 卡包", "3516 triggers"],
              note: "换届查漏走「扫上届残留」；2118 卡包 6 位跨 3 组；累积任务 group_label 必换" },
    data: [{ label: "跨玩法横比", value: "见小游戏横比报告", note: "12 个活动实例 · 春节~登月七节日", src: "reports/minigamecross" }],
    issues: [],
    assets: { report: "../reports/index.html#minigamecross", design: null, skill: "p2-metro-minigame" },
  },
  {
    id: "banquet", group: "minigame", name: "宴会做菜", icon: "🍲",
    status: "已配置 · 数值终版", origin: "2026 新增", firstAt: "2026", seasons: "1",
    oneLine: "做菜玩法 + 独立 BP，BP 经验走每日任务",
    background: "补小游戏品类，与猜酒杯的「备餐」题材同源，形成餐饮线。",
    originality: ["主活动 + 独立 BP 双活动结构", "BP 经验不走玩法产出而走 2115 每日任务，避免刷", "2185/2186 两张新表"],
    config: { main: ["21129531 主活动", "21129532 BP"], tables: ["2185", "2186", "2115 每日任务", "2112"],
              note: "币流已拍板不动；0807 数值终版" },
    data: [], issues: ["artifact v7.6 待重建"],
    assets: { report: null, design: null, skill: null },
  },

  /* ─────────────── 抽奖 / GACHA ─────────────── */
  {
    id: "marble", group: "gacha", name: "弹珠 GACHA", icon: "🔮",
    status: "已上线", origin: "2026 新增", firstAt: "2025 周年庆", seasons: "5 期（周年→万圣→圣诞→科技→拓荒）",
    oneLine: "本体抽奖弹珠机，三件套：主 GACHA + 每日礼包 + 累计任务",
    background: "本体抽奖坑位每期换玩法，弹珠是其中复用率最高的一套。fo-only 海外活动。",
    originality: [
      "89 个组件跨节日错峰复用同一套底层，新节日只换若干专属替换点",
      "schema6 与 schema3-5 两套奖励严格隔离（schema3-5 玩家绝不能拿到 schema6 大奖）",
      "升级版重做模板，拓荒首期 +47% 是本体 GACHA 坑位唯一正增长",
    ],
    config: { main: ["21127806 升级版（拓荒）"], tables: ["2116 兑换", "2121 进度", "2118 排名", "2122 排名规则", "2135 礼包", "2011"],
              note: "三件套 priority 99999 / 49997 / 49995；营收扫 2013 temp_desc 含「弹珠」按售卖日归属" },
    data: [
      { label: "三期趋势", value: "$131k → $193k → $146k", note: "科技→拓荒 +47%，本体 GACHA 坑位唯一正增长", src: "reports/minigamecross" },
      { label: "升级版首期", value: "见弹珠回归", note: "横比周年庆/万圣/圣诞/科技 4 期旧弹珠", src: "reports/marble" },
    ],
    issues: [],
    assets: { report: "../reports/index.html#marble", design: null, skill: "p2-festival-marble-gacha" },
  },
  {
    id: "wonder", group: "gacha", name: "节日巨猿 · 砸金蛋", icon: "🥚",
    status: "已上线", origin: "转正答辩", firstAt: "2025 下半年", seasons: "多期",
    oneLine: "巨猿砸金蛋，锤子消耗型抽奖",
    background: "补节日抽奖品类，锤子作为抽奖货币走礼包投放。",
    originality: ["112 components 里 110 项跨节日复用、仅 2 项节日专属（task_group / festival_wonder）",
                  "IAP 砸蛋锤礼包用 time_info.normal 数组多 actv_id 共享，一套礼包供多节日"],
    config: { main: ["21127698 复活节 2026 模板"], tables: ["2112", "2121", "2115（15 task）", "2111", "2011"], note: "" },
    data: [], issues: [],
    assets: { report: null, design: null, skill: "p2-wonder-egg-game" },
  },
  {
    id: "slot", group: "gacha", name: "老虎机 GACHA", icon: "🎲",
    status: "已落 QA", origin: "2026 新增", firstAt: "2026-08 周年庆", seasons: "1",
    oneLine: "三转轮老虎机抽奖，2188 新表 216 种排列",
    background: "本体抽奖坑位换新玩法。fo-only。",
    originality: ["2188 新表 216 排列组合", "积分 5:3:1 三档 + 免产 3", "$300-500-800-1200 四锚点",
                  "0817 兑换商店改走 2121 中转（普通 + 全服限购双组件）"],
    config: { main: ["21129553 周年庆2026-老虎机抽奖"], tables: ["2188 新表", "2116", "2121（21219755/756）", "2168 show_hud"],
              note: "⚠转轮禁投高单价硬通货；60000 币的价现有礼包容量买不起" },
    data: [], issues: ["13 处待改 + 1 个 counter（0813 数值 v8 定版后）"],
    assets: { report: null, design: null, skill: null },
  },
  {
    id: "devalue", group: "gacha", name: "贬值转盘", icon: "🎡",
    status: "已推 bugfix", origin: "2026 新增", firstAt: "2026", seasons: "1",
    oneLine: "转盘抽奖，奖池随抽取次数贬值 · 套装返场",
    background: "抽奖形态创新：用「越抽越贬值」制造早抽的紧迫感。",
    originality: ["贬值机制本身：奖池价值随抽取递减", "绑套装返场做旧资产二次销售"],
    config: { main: ["21129552"], tables: ["2121（21219734-747 共 14 组件）", "1111（代币 111130213）"], note: "待补 2111 / 1011" },
    data: [], issues: ["2111 calendar 与 1011 本地化待补"],
    assets: { report: null, design: null, skill: null },
  },
  {
    id: "bingo", group: "gacha", name: "Bingo", icon: "🔢",
    status: "已上线", origin: "转正答辩", firstAt: "2025 下半年", seasons: "多期（错峰共用壳）",
    oneLine: "连线宾果，格子随任务/付费点亮",
    background: "补节日轻玩法品类。",
    originality: ["21127035 是复用壳不是克隆：35 组件 / 51 个替换点，跨节日错峰共用一套底层"],
    config: { main: ["21127035 通用错峰壳"], tables: ["2112", "2121", "2115"], note: "复用壳非克隆，换档只改替换点" },
    data: [], issues: [],
    assets: { report: null, design: null, skill: null },
  },
  {
    id: "worldcup", group: "gacha", name: "世界杯竞猜 · 问鼎之路", icon: "🏆",
    status: "已收官", origin: "2026 新增", firstAt: "2026-07", seasons: "1",
    oneLine: "赛事竞猜，押注正确得奖励",
    background: "借世界杯赛事热度做竞猜型付费，fo-only。",
    originality: ["竞猜全链路自研（开奖重排逻辑）", "48 队头像框 + 32 队自选箱配套外显"],
    config: { main: ["21129530 问鼎之路", "21129533 世界杯竞猜签到"], tables: ["2112", "2013", "1142 头像框"],
              note: "⚠共用底层 WC 窗口后要清 box；开奖重排待推两分支" },
    data: [{ label: "收官", value: "见世界杯回归", note: "21129530 · fo · 07-04~07-20", src: "reports/worldcup" }],
    issues: [], assets: { report: "../reports/index.html#worldcup", design: null, skill: null },
  },

  /* ─────────────── 礼包与付费结构 ─────────────── */
  {
    id: "savecard", group: "pay", name: "节日特惠卡 / 省省卡", icon: "💳",
    status: "已上线", origin: "转正答辩", firstAt: "2025 下半年", seasons: "每节日一期",
    oneLine: "BP 形式：强消耗行为填充进度，投放养成线道具自选",
    background: "补充节日礼包形式，把活跃转成付费。",
    originality: [
      "加重铸矿晶 + 高级重铸矿晶两条养成线，覆盖不同 schema 玩家",
      "串联节日活动，增加节日道具礼包",
      "加升级选项满足不同 R 级购买需求",
      "二期加折上折（2011 double_coupon）",
    ],
    config: { main: ["21129505 周年庆省省卡 2026", "21127602 黑五壳（每节日克隆）"],
              tables: ["2112", "2013（内容行）", "2011 double_coupon", "1011 LC"],
              note: "每节日克隆黑五壳；LC 必重主题化；「产品位」= 2013 内容行也要换" },
    data: [
      { label: "首期营收", value: "$8,462", note: "触达付费率 4.24% · 付费玩家任务完成率 100%", src: "转正答辩 p7" },
      { label: "黑五省省卡", value: "$41,737.51", note: "售卖效果良好，后续每期加头像框和行军表情联动", src: "转正答辩 p12" },
      { label: "周年庆优化版", value: "见省省卡回归", note: "21129505 · vs 黑五一期", src: "reports/annisave" },
    ],
    issues: ["首期特惠卡选择品类少、无价格梯度", "作为节日期活动关联度较低（后续已串联）"],
    assets: { report: "../reports/index.html#annisave", design: null, skill: null },
  },
  {
    id: "afkbp", group: "pay", name: "挂机 BP", icon: "😴",
    status: "已上线", origin: "转正答辩", firstAt: "2025 周年庆 / 音乐节", seasons: "多期",
    oneLine: "挂机行为填充 BP 进度，投放养成线及节日道具",
    background: "周年庆和音乐节期间日均在线时长下滑严重，用挂机行为拉活跃并转小额付费。",
    originality: ["把「挂机」这种零操作行为做成 BP 进度来源", "加红点提示挂机收益 + 强化即时反馈"],
    config: { main: ["21127531 挂机BP-登月节2026"], tables: ["2130 BP", "2131（26 级轨）", "2112"],
              note: "独立活动，换档只动 BP 代币 + 箱" },
    data: [
      { label: "营收", value: "$12,987", note: "触达付费率 7.26%", src: "转正答辩 p8" },
      { label: "在线时长", value: "显著提高", note: "对比同期活动", src: "转正答辩 p8" },
    ],
    issues: ["16-17 级任务完成率下滑严重，持续参与率仅 57.23%", "参与触达率 57.75% 偏低"],
    assets: { report: null, design: null, skill: "reference_p2_festival_afk_bp" },
  },
  {
    id: "droptopay", group: "pay", name: "掉落转付费", icon: "🎁",
    status: "已上线", origin: "转正答辩", firstAt: "2025 下半年", seasons: "多期 · 3 套变体",
    oneLine: "从掉落池积分推进阶段奖励，商店兑换消耗",
    background: "把免费掉落行为接到付费货架上。",
    originality: ["三套变体 + 感恩节/前期单行版", "玩法层（drop 池积分 / 商店通用资源 / 阶段奖励 / retake）跨节日全通用，换档只替节日专属位"],
    config: { main: ["21127558", "21127527", "21127528"], tables: ["2112", "2111", "2121 drop_topay_show", "2116 商店"],
              note: "专属位只有 4 个：comment / show_hud / 表情包道具 / BP 道具" },
    data: [], issues: [],
    assets: { report: null, design: null, skill: "p2-droptopay-config" },
  },
  {
    id: "cityrecharge", group: "pay", name: "主城特效累充（三件套）", icon: "🏙️",
    status: "已上线", origin: "转正答辩", firstAt: "2025 下半年", seasons: "每节日一套",
    oneLine: "个人 / 服务器 / 联盟三档累充，奖主城特效",
    background: "累充品类扩展：把单人累充拆成三个社交层级。",
    originality: ["个人 / 服务器 / 联盟三件套结构，一套玩法三个竞争层级", "6 张表 25 行一次配齐，跨节日组件全沿用"],
    config: { main: ["21127582 个人", "21127583 服务器", "21127703 联盟", "21129555-557 周年庆2026"],
              tables: ["2112", "2111", "2122 rank×4", "2121 special×3", "2115 task×11", "1168 access_group"],
              note: "Jira P2DEV-141921/141924/141927" },
    data: [], issues: [],
    assets: { report: null, design: null, skill: "p2-festival-cityeffect-recharge" },
  },
  {
    id: "mecharecharge", group: "pay", name: "机甲累充", icon: "🤖",
    status: "已上线", origin: "转正答辩", firstAt: "2025 下半年", seasons: "每节日一期",
    oneLine: "单档累充，token = 本节日旗舰付费 gacha 币",
    background: "累充品类，与主城特效累充结构差异大（单 ID / 不同 ui_template / 不带排行团购）。",
    originality: ["token 绑定当期旗舰 gacha 币，把累充与抽奖绑成一条链", "三套曲线覆盖不同节日体量"],
    config: { main: ["21129560 周年庆2026-机甲累充"], tables: ["2112", "2115（11 档）"], note: "无 py 脚本，克隆 live 行 patch" },
    data: [], issues: [],
    assets: { report: null, design: null, skill: "p2-festival-mecha-recharge" },
  },
  {
    id: "flashsale", group: "pay", name: "限时抢购", icon: "⚡",
    status: "已上线", origin: "2026 新增", firstAt: "2026", seasons: "6 期",
    oneLine: "限时限量抢购，S6 / S3-5 两档",
    background: "低单价高频货架。",
    originality: ["2135/2011/2013/2121/2115/2137 全部跨节日错峰共用同一套底层（base 21127385）",
                  "新节日上线只需新建 2 行 2112 + 2 行 2111 + 改 2013 节日道具"],
    config: { main: ["21129559 周年庆-限时抢购-S3-5"], tables: ["2112×2", "2111×2", "2013 节日道具"],
              note: "换档先「删」再「换」，共用底层会串期" },
    data: [{ label: "5 期趋势", value: "$65.7k → $46.8k", note: "−29%（剔复活节非常规那期）", src: "官方口径回归" }],
    issues: [], assets: { report: null, design: null, skill: "p2-festival-flash-sale" },
  },
  {
    id: "sevenday", group: "pay", name: "七日礼包 / 预购连锁", icon: "📅",
    status: "已上线", origin: "2026 新增", firstAt: "2026", seasons: "多期",
    oneLine: "七日阶梯礼包 + $99.99 买断预购连锁",
    background: "长周期付费结构：预购买断 + 错峰免费领。",
    originality: ["预购连锁 $99.99 买断 + 错峰免费领的组合", "新七日礼包位是 2115 任务而非 2135 组件（易踩坑点）"],
    config: { main: ["21129563-566 四个七日", "21129567/568 预购连锁 schema3-5 / 6"],
              tables: ["2112×2", "2135", "2011", "2111", "2115"],
              note: "克隆必换 fincond.arg.ids；只有免费位正常＝此坑指纹" },
    data: [], issues: ["LC 还是万圣/拓荒的（周年庆四个七日）"],
    assets: { report: null, design: null, skill: "reference_p2_prechain_pkg" },
  },
  {
    id: "herochain", group: "pay", name: "英雄自选连锁", icon: "🦸",
    status: "已推 bugfix", origin: "2026 新增", firstAt: "黑五一期", seasons: "2",
    oneLine: "英雄自选 + 连锁递进礼包",
    background: "黑五档期高价值付费结构，二期做优化。",
    originality: ["二期清空 10 档 paywall_tab"],
    config: { main: ["21129506 二期（按 21127601 克隆）"], tables: ["2112", "2013（510228-237）"], note: "" },
    data: [{ label: "二期", value: "见英雄连锁回归", note: "vs 黑五一期", src: "reports/anniherochain" }],
    issues: [], assets: { report: "../reports/index.html#anniherochain", design: null, skill: null },
  },
  {
    id: "signin", group: "pay", name: "签到 / 签到 BP", icon: "✅",
    status: "已上线", origin: "转正答辩", firstAt: "2025 下半年", seasons: "每节日一期",
    oneLine: "节日签到，22 task + login_complement",
    background: "基础留存活动，后期升级为签到 BP。",
    originality: ["22 task + 补签机制", "周年庆升级为签到 BP（八表 22 行）"],
    config: { main: ["21129569 周年庆2026-签到BP"], tables: ["2112", "2111", "2115 task pool"],
              note: "仅 4 字段节日专属：constant / ui_template / show_hud / banner_url" },
    data: [], issues: ["自选箱 desc 具名旧皮肤"],
    assets: { report: null, design: null, skill: "p2-festival-signin" },
  },
  {
    id: "weekcard", group: "pay", name: "周卡 / 打折折扣礼包", icon: "🏷️",
    status: "已上线", origin: "转正答辩", firstAt: "2025 下半年", seasons: "多期",
    oneLine: "周期性小额付费 + 折扣礼包",
    background: "补小额付费品类，打折卡形式促进消费。",
    originality: ["打折卡形式（转正答辩 p12 措施之一）"],
    config: { main: ["21128220 KVK456 一次性周卡2-活跃"], tables: ["2112", "2013"], note: "" },
    data: [], issues: ["中低 R 对常规折扣逐渐免疫（转正答辩反思）"],
    assets: { report: null, design: null, skill: null },
  },

  /* ─────────────── 外显 / 收藏 ─────────────── */
  {
    id: "marchemoji", group: "cosmetic", name: "行军表情 / 行军特效", icon: "🎭",
    status: "已上线", origin: "转正答辩", firstAt: "2025 下半年", seasons: "每节日一期",
    oneLine: "行军路径上的表情与特效外显",
    background: "表情包售卖效果不及预期、内容表现单一，需要重做主题方向。",
    originality: ["总结高热表情主题，确定后续设计方向", "借鉴竞品表现形式重做", "与省省卡联动售卖"],
    config: { main: ["21129534 登月-行军表情", "21129536 登月-行军特效"],
              tables: ["2112", "2135", "2121", "2011", "2013", "1111", "1180", "1168", "1365", "1511", "1512", "2111"],
              note: "联动礼包家族 = 表情 + 特效 + 框 三款，回归要合并成一族看" },
    data: [
      { label: "万圣节行军表情", value: "$11,127.7", note: "售卖量突破历史新高", src: "转正答辩 p12" },
      { label: "联动礼包家族 6 期", value: "$40.0k → $29.4k", note: "−26%（表情+特效+框合并口径）", src: "官方口径回归" },
    ],
    issues: [], assets: { report: "../reports/index.html#moonunite", design: null, skill: "p2-unite-gift-pack" },
  },
  {
    id: "avatar", group: "cosmetic", name: "头像框", icon: "🖼️",
    status: "已上线", origin: "转正答辩", firstAt: "2025 下半年", seasons: "每节日一期",
    oneLine: "角色头像外圈装饰，含动态框",
    background: "外显品类扩展，做首个可变化动态头像框。",
    originality: ["首个可变化动态头像框（转正答辩 p12）", "世界杯 48 队框系列 + 32 队自选箱", "三段式稀有度分档"],
    config: { main: ["21129535 登月-头像框礼包"], tables: ["1142 avatar_frame", "2112", "2013"],
              note: "头像框不走 1168 跳转；1142 屏蔽页签 = 主页签去掉 XX 的副本" },
    data: [{ label: "持有率", value: "96.3%", note: "外显品类在本项目接近全民行为", src: "内部实证" }],
    issues: [], assets: { report: null, design: null, skill: null },
  },
  {
    id: "cityskin", group: "cosmetic", name: "主城皮肤 / 主城套装", icon: "🏛️",
    status: "已上线", origin: "转正答辩", firstAt: "2025 下半年", seasons: "7 套套装 / 124 张皮肤",
    oneLine: "整座城的外观皮肤，套装 = 2 皮肤 + 2 挂件 + 1 特效",
    background: "首个可变化动态主城外观（与头像框同期）。",
    originality: ["首个可变化动态主城外观", "套装结构：集齐 5 件解锁最终形态", "染色能力（dyeing_skin）做到一皮四色"],
    config: { main: ["13891001-1007 七套套装"], tables: ["1312 city_skin（124 行）", "1388 组件（20 行）", "1389 套装（7 套）", "1511", "1512", "1111"],
              note: "1312 的 display_key 与 skin_level 都填「模型」；1111 才填「图标」" },
    data: [{ label: "存量", value: "124 张皮肤 / 7 套套装", note: "quality 分布 q3=57 / q4=37 / q5=18", src: "1312 实测" }],
    issues: ["一套 5 件集齐即终点，一期最多 5 个可售单位", "换新即弃旧，旧付费随新内容贬值", "dyeing_skin 换色引擎 2026 全年新增 0 行"],
    assets: { report: null, design: "../docs/myriad_city_design/index.html", skill: null },
  },
  {
    id: "nameplate", group: "cosmetic", name: "铭牌（聊天框皮肤）", icon: "💬",
    status: "已上线", origin: "2026 新增", firstAt: "2026", seasons: "每节日一期",
    oneLine: "聊天框 + 对话名 + 发言者颜色一整套皮肤",
    background: "外显品类扩展到社交界面。",
    originality: ["把外显从「地图/主城」扩展到「聊天界面」", "4 字主题 + 一句氛围 desc 的命名范式"],
    config: { main: ["1173 chat_skin"], tables: ["1173", "1111", "1011"], note: "5 个 hex 色按聊天框美术取色" },
    data: [], issues: [], assets: { report: null, design: null, skill: "p2-festival-nameplate" },
  },
  {
    id: "decoration", group: "cosmetic", name: "装饰物 / 集卡册 / 勋章", icon: "🗿",
    status: "已上线", origin: "转正答辩 + 2026", firstAt: "2025 下半年", seasons: "多期",
    oneLine: "可升级星级的主城装饰 + 图鉴收集 + 段位勋章",
    background: "投放载体：挖孔等小游戏的产出出口。",
    originality: ["装饰物支持涂饰（上色 24h 获额外 buff + 主动技能）", "四周年纪念勋章一年一枚独立 class", "集卡册收集线"],
    config: { main: ["2148 event_decroation_level", "1159 player_badge", "60011009 集卡册"],
              tables: ["2148", "1118 building", "1127", "1111", "2171 技能", "1159", "1393"],
              note: "10 星装饰 100% 支持涂饰；粉刷按钮不显示 99% 是 1118 function 漏 11301603" },
    data: [], issues: ["四周年勋章还没挂进集卡册 60011009 rewards"],
    assets: { report: null, design: null, skill: null },
  },

  /* ─────────────── 立项 / 未上线 ─────────────── */
  {
    id: "sportsmeet", group: "pitch", name: "猿力全能赛（节日运动会元系统）", icon: "🏅",
    status: "立项论证中", origin: "立项", firstAt: "2026-07", seasons: "—",
    oneLine: "不新做玩法，给现有全部节日活动加一层运动员派遣与增益",
    background: "现有付费点开采到顶（20/22 族过峰）。元系统不需要证明「好玩」——游玩发生在已上线活动里。",
    originality: [
      "元系统形态：抽运动员 → 派遣到具体活动 → 该活动内获增益 → 产金牌 → 养成",
      "全活动挂载表穷举（可信度来源）",
      "增益四分法与「会不会吃自己营收」专章：前期增益硬封顶 + 后期收益只落本系统内部",
      "UR 不可直抽（经济命门）",
    ],
    config: { main: ["—（未配置）"], tables: ["拟挂现有全部节日活动"], note: "机制已简化定版；策划案 HTML 仍是旧口径" },
    data: [], issues: ["策划案 HTML 与 2026-07-27 定版不一致（check_doc 报 28 行旧口径残留）"],
    assets: { report: null, design: "../docs/sports_meet_design/index.html", skill: null },
  },
  {
    id: "myriadcity", group: "pitch", name: "万象主城（主城外观装配层）", icon: "🌆",
    status: "立项论证中", origin: "立项", firstAt: "2026-08", seasons: "—",
    oneLine: "主城拆成城基 + 城市本体两段分别售卖，自由组合 + 换色",
    background: "主城外观是存量最大（124 张）但复用率最低（同时只能穿 1 张）的品类，付费深度一期 5 件即封顶。",
    originality: [
      "城基 ×1 + 城市本体 ×1（主力付费）+ 城辉 ×1 + 各自独立换色",
      "槽位数永久固定 3 个且必须小于件数 —— 取舍才让第 N 件仍有价值",
      "璀璨态是装配状态而非单品，门槛跟随当期 → 永不封顶",
      "收藏度持有即计分，解决「换新即弃旧」",
      "不替代节日主城套装，而是给它装上后续价值",
    ],
    config: { main: ["—（未配置）"], tables: ["1312", "1388", "1389（需槽位化改造）", "1511", "1512"],
              note: "dyeing_skin 换色引擎已上线且闲置；1389 items 本就是定长 5 槽" },
    data: [{ label: "首期可售单位", value: "17", note: "对照现有节日套装单期 5 → 3.4×", src: "docs/myriad_city_design" }],
    issues: ["属性 buff 口径未定（首期落表前必须定版）", "挂载点规范必须在美术开工前定死"],
    assets: { report: null, design: "../docs/myriad_city_design/index.html",
              devspec: "https://docs.google.com/spreadsheets/d/1t0dnVFTmIxIxVPVXBqQS69Df4RFu0ikhEdfRqthWmIU/edit",
              skill: null },
  },
  {
    id: "pinball", group: "pitch", name: "宇宙弹弹乐", icon: "🌌",
    status: "草案", origin: "立项", firstAt: "2026", seasons: "—",
    oneLine: "物理弹珠积分 + 跨服总榜",
    background: "小游戏品类扩展，物理玩法在项目内是空白。",
    originality: ["物理弹珠积分玩法", "跨服总榜（现有活动少见的跨服竞争）"],
    config: { main: ["—（未配置）"], tables: ["需程序立项"], note: "HTML 含原型" },
    data: [], issues: ["需程序立项"], assets: { report: null, design: null, skill: null },
  },
  {
    id: "cardrpg", group: "pitch", name: "节日卡牌 RPG（猩球对决）", icon: "🃏",
    status: "已推翻", origin: "立项", firstAt: "2026-07", seasons: "—",
    oneLine: "五人小队自动战斗 + 卡牌养成 + 爬塔",
    background: "想补主玩法层。",
    originality: ["全卡牌化经济（英雄卡 + 装备卡一套）", "零决策自动互殴 + 编成自由化", "对战规则说明书写到可实现级"],
    config: { main: ["—（未配置）"], tables: ["—"], note: "v1.1 → v1.8 八个版本迭代" },
    data: [], issues: ["被否：① 保不了「新玩法好不好玩」② 太偏策划向，运营岗应做活动向"],
    assets: { report: null, design: "../docs/card_rpg_design/index.html", skill: null },
  },
];
